CREATE INDEX idx_address_balance ON address (balance);
CREATE UNIQUE INDEX idx_transaction_txid ON tx (txid);
CREATE UNIQUE INDEX idx_transaction_hash ON tx (hash);
CREATE INDEX idx_transaction_timereceived ON tx (timereceived);
CREATE INDEX idx_transaction_fee ON tx (fee);
CREATE INDEX idx_transaction_size ON tx (size);
CREATE INDEX idx_transaction_vsize ON tx (vsize);
CREATE INDEX idx_transaction_block_hash ON tx (block_hash);
CREATE INDEX idx_address_tx_address_id ON address_tx (address_id);
CREATE INDEX idx_address_tx_transaction_id ON address_tx (transaction_id);
CREATE INDEX idx_props_property ON props (property);
